Changes to config and manifest for deploying on govcloud
18F/ffd-microsite pull request #60
Opened 2017-01-03 21:33 UTC by donjo

This fixes the URL and changes the directory where static assets are served so the page loads.

2017-01-04 19:25 UTC, fureigh approved these changes
LGTM!

2017-01-04 19:26 UTC, fureigh commented on config.toml
> +baseurl = "https://ffd-microsite-staging.app.cloud.gov/"
@donjo This is meant to be staging, correct?

2017-01-04 19:35 UTC, donjo commented on config.toml
> +baseurl = "https://ffd-microsite-staging.app.cloud.gov/"
correct. there's probably a better way to do this where both the staging and master are defined in the same config but as it's set up now they need the full baseurl defined to ensure the static assets load correctly in their respective builds/branches. I'll check in with you directly to talk about some better ways to do this.

2017-01-04 22:58 UTC, fureigh requested changes

2017-01-04 22:58 UTC, fureigh commented on .travis.yml
> +  - SITE_BASEURL_PRODUCTION="https://ffd-microsite-production.apps.cloud.gov/" SITE_BASEURL_STAGING="https://ffd-microsite-staging.apps.cloud.gov/"
Thanks, @donjo! Two questions:
1) Shouldn't these be `.app.cloud.gov`?
2) Are they meant to be on the same line?

2017-01-04 23:04 UTC, donjo commented on .travis.yml
> +  - SITE_BASEURL_PRODUCTION="https://ffd-microsite-production.apps.cloud.gov/" SITE_BASEURL_STAGING="https://ffd-microsite-staging.apps.cloud.gov/"
1. doh! yes.
2. not sure. they were before I got here but unless this breaks something I'll change it to two lines for readability.

2017-01-05 17:37 UTC, donjo commented on .travis.yml
> +  - SITE_BASEURL_PRODUCTION="https://ffd-microsite-production.apps.cloud.gov/" SITE_BASEURL_STAGING="https://ffd-microsite-staging.apps.cloud.gov/"
Tried separating to different lines but it seems like travis parsed things differently and one of the build was failing.

2017-01-05 20:47 UTC, fureigh approved these changes
Hmm. Okay! Perhaps open a tiny `help wanted` ticket as follow-up, in case someone has time to see why Travis was objecting. But I'm fine with this as-is.

2017-01-05 20:49 UTC, merged